//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessTest.EntityFrameworkPriklady.DatabasePrvni
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RadovanDBEntities : DbContext
    {
        public RadovanDBEntities()
            : base("name=RadovanDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<oddeleni> oddeleni { get; set; }
        public virtual DbSet<zamestnanec> zamestnanec { get; set; }
    }
}
