//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessTest.EntityFrameworkPriklady.DatabasePrvni
{
    using System;
    using System.Collections.Generic;
    
    public partial class oddeleni
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public oddeleni()
        {
            this.zamestnanec = new HashSet<zamestnanec>();
        }
    
        public int id_oddeleni { get; set; }
        public string nazev { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zamestnanec> zamestnanec { get; set; }
    }
}
